name: Build & Deploy Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # required for gh-pages deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate connector docs
        run: |
          shopt -s nullglob
          for f in manifests/*.{yml,yaml,json}; do
            slug=$(basename "$f")
            slug="${slug%.*}"
            python scripts/generate_doc.py "$f" "docs/connectors/${slug}.md"
          done
      - name: Build & Deploy MkDocs site
        uses: mkdocs/actions-gh-pages@v1
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          extra_args: --strict 